// Testa apps-script/Code.gs com serviços simulados. Uso: node test/backend-test.js
const { makeGas } = require('./gas-mock');
const g = makeGas();
let fails = 0;
const ok = (cond, msg) => { console.log((cond ? 'ok   ' : 'FALHA') + ' · ' + msg); if (!cond) fails++; };

ok(g.ctx.setup().startsWith('Pronto'), 'setup cria abas e pasta');
ok(g.get('hora').ok && typeof g.get('hora').now === 'number', 'GET devolve a hora do servidor');
let r = g.post({ action: 'cadastrar', nome: 'D', email: 'x@y.com', senha: '123456' });
ok(!r.ok && /nome/.test(r.erro), 'recusa nome curto');
r = g.post({ action: 'cadastrar', nome: 'Dhione', email: 'email-ruim', senha: '123456' });
ok(!r.ok && /e-mail/.test(r.erro), 'recusa e-mail inválido');
r = g.post({ action: 'cadastrar', nome: 'Dhione', email: 'dhione@exemplo.com', senha: '123' });
ok(!r.ok && /senha/.test(r.erro), 'recusa senha curta');
r = g.post({ action: 'cadastrar', nome: 'Dhione', email: 'Dhione@Exemplo.com', senha: 'segredo1' });
ok(r.ok && r.token && r.usuario.email === 'dhione@exemplo.com', 'cria conta e já entra');
const t1 = r.token;
r = g.post({ action: 'cadastrar', nome: 'Outro', email: 'dhione@exemplo.com', senha: 'segredo2' });
ok(!r.ok && /Já existe/.test(r.erro), 'não deixa repetir e-mail');
const row = g.gas._sheets.get('contas').rows[1];
ok(row[4] && row[4] !== 'segredo1' && row[4].length > 20, 'senha guardada só como hash');
r = g.post({ action: 'entrar', email: 'dhione@exemplo.com', senha: 'errada' });
ok(!r.ok, 'senha errada não entra');
r = g.post({ action: 'entrar', email: 'DHIONE@exemplo.com', senha: 'segredo1' });
ok(r.ok && r.token && r.mundo === null, 'entra com e-mail em maiúsculas; ainda sem mundo');
const t2 = r.token;
r = g.post({ action: 'carregar', token: t2 });
ok(r.ok && r.dados === null, 'carregar sem mundo devolve vazio');
const save = JSON.stringify({ v: 1, game: 'genesis', t: 1234, people: [] });
r = g.post({ action: 'salvar', token: t2, dados: save, resumo: { ano: 2, estacao: 'Verão', dia: 3, anos: 1, vivos: 2, nomes: 'Iara, Aruã', local: 'à beira do rio' } });
ok(r.ok && r.savedAt > 0, 'salva o mundo no Drive');
const f1 = g.gas._sheets.get('contas').rows[1][7];
r = g.post({ action: 'salvar', token: t2, dados: save.replace('1234', '5678'), resumo: { ano: 2, anos: 1, vivos: 2 } });
ok(r.ok && g.gas._sheets.get('contas').rows[1][7] === f1, 'salvar de novo reaproveita o mesmo arquivo');
r = g.post({ action: 'carregar', token: t1 });
ok(r.ok && JSON.parse(r.dados).t === 5678 && r.savedAt > 0, 'outra sessão da mesma conta carrega o save mais novo');
r = g.post({ action: 'salvar', token: t2, dados: '{quebrado' });
ok(!r.ok && /corrompido/.test(r.erro), 'recusa save corrompido');
r = g.post({ action: 'salvar', token: 'token-falso', dados: save });
ok(!r.ok && r.sessao === false, 'token inválido pede novo login');
g.post({ action: 'cadastrar', nome: 'Maria', email: 'maria@exemplo.com', senha: 'segredo3' });
const tm = g.post({ action: 'entrar', email: 'maria@exemplo.com', senha: 'segredo3' }).token;
g.post({ action: 'salvar', token: tm, dados: save, resumo: { ano: 5, anos: 4, vivos: 6, local: 'ao pé da montanha' } });
r = g.post({ action: 'ranking' });
ok(r.ok && r.lista.length === 2 && r.lista[0].nome === 'Maria' && r.lista[0].anos === 4, 'ranking ordena por anos sobrevividos');
r = g.post({ action: 'sair', token: t2 });
ok(r.ok, 'sair encerra a sessão');
r = g.post({ action: 'carregar', token: t2 });
ok(!r.ok && r.sessao === false, 'token de quem saiu não vale mais');
r = g.post({ action: 'apagar', token: t1 });
ok(r.ok && g.post({ action: 'carregar', token: t1 }).dados === null, 'apagar mundo limpa o save');
r = g.post({ action: 'qualquer' });
ok(!r.ok && /desconhecida/.test(r.erro), 'ação desconhecida responde erro');
const t0 = Date.now(); for (let i = 0; i < 5; i++) g.post({ action: 'entrar', email: 'maria@exemplo.com', senha: 'segredo3' });
console.log('\nentrar (com hash de senha) leva ~' + Math.round((Date.now() - t0) / 5) + ' ms no Node');
console.log(fails ? fails + ' falha(s)' : 'tudo certo');
process.exit(fails ? 1 : 0);
